spring:
  main:
    web-application-type: servlet
  datasource:
    url: jdbc:postgresql://dpg-ctomakjtq21c73cus4p0-a.frankfurt-postgres.render.com:5432/kubo_db_rhn2
    username: kubo_db_rhn2_user
    password: 1qFFKmdni7TOkKQKy7LzohzQ5uZAFmg5
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  flyway:
    enabled: true
    encoding: utf-8
    schemas: addressbook
    create-schemas: true
    default-schema: addressbook
server:
  servlet:
    context-path: /addressbook
  port: 8080
  error:
    include-message: always
client:
  country-url: https://restcountries.com
  city-url: https://opzoeken-postcode.be
  street-url: https://www.schoolvoorbeeld.be
